# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa160fe29502ac12f978fc8d036bade6a21832c11d19e744214abe5eb028c48ea9dc4a0ff67f98cbf173168cc0c44e1fc04213de6064250349c7890304b6672e

test:
  secret_key_base: c0fb70023821042fd97e360376e4b720a0ae3936a64780476b5837989341cba3eec56f7f5a53388f4c3cae0d8be6558277b997b44cfd4e2f11bcb3f6fc79fe1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
